version: '3.5'

services:
  web:
    #image: ${DOCKER_REGISTRY-}kamchatkatravelweb
    build:
      context: .
      dockerfile: KamchatkaTravel.Web/Dockerfile
      #network: webnetwork
    ports:
        - "8080:80"
    restart: unless-stopped
    

  admin:
    #image: ${DOCKER_REGISTRY-}kamchatkatravelwebdashboard
    build:
      context: .
      dockerfile: KamchatkaTravel.WebDashboard/Dockerfile
      #network: adminnetwork
    ports:
        - "8081:80"
    restart: unless-stopped

#networks:
#  webnetwork:
#    name: webnetwork
#    driver: bridge
#  adminnetwork:
#    name: adminnetwork
#    driver: bridge